--Q1. What is the total revenue generated by male vs. female customers?
SELECT gender, SUM(purchase_amount) AS total_revenue
FROM customer
GROUP BY gender
ORDER BY total_revenue DESC
--Q2. Which customers used a discount but still spent more than the average purchase amount? 
SELECT customer_id, discount_applied, purchase_amount
FROM customer
WHERE discount_applied = 'Yes'
	AND purchase_amount > (SELECT AVG(purchase_amount) FROM customer)
--Q3. Which are the top 5 products with the highest average review rating?
SELECT item_purchased, ROUND(AVG(CAST(review_rating AS NUMERIC)), 2) AS avg_review_rating
FROM customer
GROUP BY item_purchased
ORDER BY avg_review_rating DESC
LIMIT 5
--Q4. Compare the average Purchase Amounts between Standard and Express Shipping. 
SELECT shipping_type, ROUND(AVG(purchase_amount), 2) AS avg_purchase_amount
FROM customer
WHERE shipping_type IN ('Standard', 'Express')
GROUP BY shipping_type
ORDER BY avg_purchase_amount DESC
--Q5. Do subscribed customers spend more? Compare average spend and total revenue 
--between subscribers and non-subscribers.
SELECT subscription_status,
	   COUNT(customer_id) AS customer,
	   ROUND(AVG(purchase_amount), 2) AS avg_spend,
	   SUM(purchase_amount) AS total_revenue
FROM customer
GROUP BY subscription_status
ORDER BY customer DESC
--Q6. Which 5 products have the highest percentage of purchases with discounts applied?
SELECT item_purchased, 
	   ROUND(100*SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END)/COUNT(*), 2) as discount_rate
FROM customer
GROUP BY item_purchased
LIMIT 5
--Q7. Segment customers into New, Returning, and Loyal based on their total 
-- number of previous purchases, and show the count of each segment. 
WITH customer_type AS(
	SELECT customer_id, previous_purchases,
	CASE
		WHEN previous_purchases = 1 THEN 'New'
		WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
		ELSE 'Loyal'
	END AS customer_segment
	FROM customer
)

SELECT customer_segment, COUNT(customer_id)
FROM customer_type
GROUP BY customer_segment
--Q8. What are the top 3 most purchased products within each category?
WITH total_product_purchased AS(
	SELECT item_purchased, category, COUNT(*) AS number_purchased
	FROM customer
	GROUP BY item_purchased, category
),

	product_rank AS(
	SELECT category,
		   item_purchased,
		   number_purchased,
	       ROW_NUMBER() OVER(
		   PARTITION BY category
		   ORDER BY number_purchased DESC) AS item_rank
	FROM total_product_purchased
)

SELECT category, item_purchased, number_purchased, item_rank
FROM product_rank
WHERE item_rank <= 3

--Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
SELECT subscription_status, COUNT(customer_id) AS repeat_buyers
FROM customer
WHERE previous_purchases > 5
GROUP BY subscription_status
--Q10. What is the revenue contribution of each age group?
SELECT age_group, SUM(purchase_amount) AS total_revenue
FROM customer
GROUP BY age_group
ORDER BY total_revenue DESC